{
 "title": "Observability Dashboard",
 "description": "Micrometer/Prometheus scrape (K8s). Adapted from OTel dashboard for /actuator/prometheus.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\"}, application)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$service\", namespace=\"$namespace\", area=\"heap\"}, id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$service\", namespace=\"$namespace\", area=\"nonheap\"}, id)"
    }
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pool",
    "query": {
     "query": "label_values(jvm_buffer_memory_used_bytes{application=\"$service\", namespace=\"$namespace\"}, id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  increase (\n    http_server_requests_seconds_count{application=\"$service\", namespace=\"$namespace\"}[$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "HTTP Request Status Codes Ratio",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace (\n    increase (\n      http_server_requests_seconds_count{application=\"$service\", namespace=\"$namespace\"}[$__range]\n    ),\n    \"status\",\n    \"Unknown\",\n    \"status\",\n    \"\"\n  )\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (uri, method) (\n  rate (\n    http_server_requests_seconds_count{application=\"$service\", namespace=\"$namespace\"}[5m]\n  )\n)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (uri, method) (\n  increase(\n    http_server_requests_seconds_count{\n      application=\"$service\", namespace=\"$namespace\", \n      status=~\"2..|3..\"\n    }[$__range]\n  )\n)"
    },
    {
     "expr": "sum by (uri, method) (\n  increase(\n    http_server_requests_seconds_count{\n      application=\"$service\", namespace=\"$namespace\", \n      status=~\"4..|5..\"\n    }[$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Average HTTP Request Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri, method) (\n  increase (\n    http_server_requests_seconds_sum{application=\"$service\", namespace=\"$namespace\"}[$__range]\n  )\n)\n/\nsum by (uri, method) (\n  increase (\n    http_server_requests_seconds_count{application=\"$service\", namespace=\"$namespace\"}[$__range]\n  )\n)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "ClassLoading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Class Current Loading",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{application=\"$service\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Total Class Loaded",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_count_classes_total{application=\"$service\", namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  },
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{application=\"$service\", namespace=\"$namespace\"}) / 3600"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$service\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "JVM Observability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory Pool(Heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$service\", namespace=\"$namespace\", id=~\"$jvm_memory_pool_heap\"}"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$service\", namespace=\"$namespace\", id=~\"$jvm_memory_pool_heap\"}"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$service\", namespace=\"$namespace\", id=~\"$jvm_memory_pool_heap\"}"
      }
     ]
    },
    {
     "title": "JVM Memory Pool(Non-Heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$service\", namespace=\"$namespace\", id=~\"$jvm_memory_pool_nonheap\"}"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$service\", namespace=\"$namespace\", id=~\"$jvm_memory_pool_nonheap\"}"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$service\", namespace=\"$namespace\", id=~\"$jvm_memory_pool_nonheap\"}"
      }
     ]
    },
    {
     "title": "JVM Duration Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{application=\"$service\", namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Buffer Pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$service\", namespace=\"$namespace\", id=~\"$jvm_buffer_pool\"}"
      }
     ]
    },
    {
     "title": "JVM Thread Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{application=\"$service\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Total Time For Garbage Collection Per Service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_sum{application=\"$service\", namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  },
  { "title": "CPU Observability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage Per Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"$service\", namespace=\"$namespace\"} * 100"
    },
    {
     "expr": "jvm_classes_loaded_count_classes_total{application=\"$service\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU Ratio Used Per Service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"$service\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "JVM CPU Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{application=\"$service\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Total CPU Usage Rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "avg(process_cpu_usage{application=\"$service\", namespace=\"$namespace\"}) * 100"
    }
   ]
  },
  {
   "title": "Top 5 Rate Using CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "topk(5, process_cpu_usage{application=\"$service\", namespace=\"$namespace\"} * 100)"
    }
   ]
  },
  {
   "title": "Memory Used After Last Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_gc_live_data_size_bytes{application=\"$service\", namespace=\"$namespace\"}"
    }
   ]
  },
  { "title": "Memory Observability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Memory Usage Per Service (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by(application) (jvm_memory_used_bytes{application=\"$service\", namespace=\"$namespace\"}) / 1048576"
    }
   ]
  },
  {
   "title": "Memory commiited (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum by(application) (jvm_memory_committed_bytes{application=\"$service\", namespace=\"$namespace\"}) / 1048576"
    }
   ]
  },
  {
   "title": "Memory limit (Mb)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(application) (jvm_memory_max_bytes{application=\"$service\", namespace=\"$namespace\"}) / 1048576"
    }
   ]
  },
  {
   "title": "Prometheus Memory Used (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum(avg_over_time(jvm_memory_used_bytes{application=\"$service\", namespace=\"$namespace\"}[5m])) / 1048576"
    }
   ]
  },
  {
   "title": "Database Connection Observability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true
  },
  {
   "title": "Max Connection Allowed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "hikaricp_connections_max{application=\"$service\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number Of Connection In Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"$service\", namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}